services:
  apexf1-db:
    image: 'pgvector/pgvector:pg16'
    container_name: apexf1-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./apexf1_data:/var/lib/postgresql/data
    restart: always